// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime

public enum DeleteScheduledActionOutputError: Swift.Error, Swift.Equatable {
    case scheduledActionNotFoundFault(ScheduledActionNotFoundFault)
    case unauthorizedOperation(UnauthorizedOperation)
    case unknown(UnknownAWSHttpServiceError)
}
