// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension IoTAnalyticsClientTypes.ChannelMessages: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case s3Paths
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let s3Paths = s3Paths {
            var s3PathsContainer = encodeContainer.nestedUnkeyedContainer(forKey: .s3Paths)
            for s3pathchannelmessages0 in s3Paths {
                try s3PathsContainer.encode(s3pathchannelmessages0)
            }
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let s3PathsContainer = try containerValues.decodeIfPresent([Swift.String?].self, forKey: .s3Paths)
        var s3PathsDecoded0:[Swift.String]? = nil
        if let s3PathsContainer = s3PathsContainer {
            s3PathsDecoded0 = [Swift.String]()
            for string0 in s3PathsContainer {
                if let string0 = string0 {
                    s3PathsDecoded0?.append(string0)
                }
            }
        }
        s3Paths = s3PathsDecoded0
    }
}
