// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension AddFlowOutputsInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case outputs = "outputs"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let outputs = outputs {
            var outputsContainer = encodeContainer.nestedUnkeyedContainer(forKey: .outputs)
            for __listofaddoutputrequest0 in outputs {
                try outputsContainer.encode(__listofaddoutputrequest0)
            }
        }
    }
}
