// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension CloudWatchLogsClientTypes {
    /// Represents the search status of a log stream.
    public struct SearchedLogStream: Swift.Equatable {
        /// The name of the log stream.
        public var logStreamName: Swift.String?
        /// Indicates whether all the events in this log stream were searched.
        public var searchedCompletely: Swift.Bool?

        public init (
            logStreamName: Swift.String? = nil,
            searchedCompletely: Swift.Bool? = nil
        )
        {
            self.logStreamName = logStreamName
            self.searchedCompletely = searchedCompletely
        }
    }

}
