// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension LookoutMetricsClientTypes.TimeSeriesFeedback: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case isAnomaly = "IsAnomaly"
        case timeSeriesId = "TimeSeriesId"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let isAnomaly = self.isAnomaly {
            try encodeContainer.encode(isAnomaly, forKey: .isAnomaly)
        }
        if let timeSeriesId = self.timeSeriesId {
            try encodeContainer.encode(timeSeriesId, forKey: .timeSeriesId)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let timeSeriesIdDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .timeSeriesId)
        timeSeriesId = timeSeriesIdDecoded
        let isAnomalyDecoded = try containerValues.decodeIfPresent(Swift.Bool.self, forKey: .isAnomaly)
        isAnomaly = isAnomalyDecoded
    }
}
