// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ListTagsForResourceOutputResponse: Swift.Equatable {
    /// The tags associated with the specified topic.
    public var tags: [SnsClientTypes.Tag]?

    public init (
        tags: [SnsClientTypes.Tag]? = nil
    )
    {
        self.tags = tags
    }
}
