// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ListAccessPreviewsInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        return "/access-preview"
    }
}
