// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// An object that that contains the Message ID of a Voice message that was sent successfully.
public struct SendVoiceMessageOutputResponse: Swift.Equatable {
    /// A unique identifier for the voice message.
    public var messageId: Swift.String?

    public init (
        messageId: Swift.String? = nil
    )
    {
        self.messageId = messageId
    }
}
