// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ListLocalDisksOutputResponse: Swift.Equatable {
    /// A JSON object containing the following fields:
    ///
    /// * [ListLocalDisksOutput$Disks]
    public var disks: [StorageGatewayClientTypes.Disk]?
    /// The Amazon Resource Name (ARN) of the gateway. Use the [ListGateways] operation to return a list of gateways for your account and Amazon Web Services Region.
    public var gatewayARN: Swift.String?

    public init (
        disks: [StorageGatewayClientTypes.Disk]? = nil,
        gatewayARN: Swift.String? = nil
    )
    {
        self.disks = disks
        self.gatewayARN = gatewayARN
    }
}
