// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct CreateTransitGatewayVpcAttachmentInput: Swift.Equatable {
    /// Checks whether you have the required permissions for the action, without actually making the request, and provides an error response. If you have the required permissions, the error response is DryRunOperation. Otherwise, it is UnauthorizedOperation.
    public var dryRun: Swift.Bool?
    /// The VPC attachment options.
    public var options: EC2ClientTypes.CreateTransitGatewayVpcAttachmentRequestOptions?
    /// The IDs of one or more subnets. You can specify only one subnet per Availability Zone. You must specify at least one subnet, but we recommend that you specify two subnets for better availability. The transit gateway uses one IP address from each specified subnet.
    /// This member is required.
    public var subnetIds: [Swift.String]?
    /// The tags to apply to the VPC attachment.
    public var tagSpecifications: [EC2ClientTypes.TagSpecification]?
    /// The ID of the transit gateway.
    /// This member is required.
    public var transitGatewayId: Swift.String?
    /// The ID of the VPC.
    /// This member is required.
    public var vpcId: Swift.String?

    public init (
        dryRun: Swift.Bool? = nil,
        options: EC2ClientTypes.CreateTransitGatewayVpcAttachmentRequestOptions? = nil,
        subnetIds: [Swift.String]? = nil,
        tagSpecifications: [EC2ClientTypes.TagSpecification]? = nil,
        transitGatewayId: Swift.String? = nil,
        vpcId: Swift.String? = nil
    )
    {
        self.dryRun = dryRun
        self.options = options
        self.subnetIds = subnetIds
        self.tagSpecifications = tagSpecifications
        self.transitGatewayId = transitGatewayId
        self.vpcId = vpcId
    }
}
