// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DescribeLocalGatewayRouteTablesOutputResponse: Swift.Equatable {
    /// Information about the local gateway route tables.
    public var localGatewayRouteTables: [Ec2ClientTypes.LocalGatewayRouteTable]?
    /// The token to use to retrieve the next page of results. This value is null when there are no more results to return.
    public var nextToken: Swift.String?

    public init (
        localGatewayRouteTables: [Ec2ClientTypes.LocalGatewayRouteTable]? = nil,
        nextToken: Swift.String? = nil
    )
    {
        self.localGatewayRouteTables = localGatewayRouteTables
        self.nextToken = nextToken
    }
}
