// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Contains the output of DescribeNetworkInterfaceAttribute.
public struct DescribeNetworkInterfaceAttributeOutputResponse: Swift.Equatable {
    /// The attachment (if any) of the network interface.
    public var attachment: Ec2ClientTypes.NetworkInterfaceAttachment?
    /// The description of the network interface.
    public var description: Ec2ClientTypes.AttributeValue?
    /// The security groups associated with the network interface.
    public var groups: [Ec2ClientTypes.GroupIdentifier]?
    /// The ID of the network interface.
    public var networkInterfaceId: Swift.String?
    /// Indicates whether source/destination checking is enabled.
    public var sourceDestCheck: Ec2ClientTypes.AttributeBooleanValue?

    public init (
        attachment: Ec2ClientTypes.NetworkInterfaceAttachment? = nil,
        description: Ec2ClientTypes.AttributeValue? = nil,
        groups: [Ec2ClientTypes.GroupIdentifier]? = nil,
        networkInterfaceId: Swift.String? = nil,
        sourceDestCheck: Ec2ClientTypes.AttributeBooleanValue? = nil
    )
    {
        self.attachment = attachment
        self.description = description
        self.groups = groups
        self.networkInterfaceId = networkInterfaceId
        self.sourceDestCheck = sourceDestCheck
    }
}
