// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DetachClassicLinkVpcInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        return "/"
    }
}
