// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension Ec2ClientTypes {
    /// Configuration settings for creating and managing pre-provisioned snapshots for a fast-launch enabled Windows AMI.
    public struct FastLaunchSnapshotConfigurationResponse: Swift.Equatable {
        /// The number of pre-provisioned snapshots requested to keep on hand for a fast-launch enabled Windows AMI.
        public var targetResourceCount: Swift.Int?

        public init (
            targetResourceCount: Swift.Int? = nil
        )
        {
            self.targetResourceCount = targetResourceCount
        }
    }

}
