// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetHostReservationPurchasePreviewOutputResponse: Swift.Equatable {
    /// The currency in which the totalUpfrontPrice and totalHourlyPrice amounts are specified. At this time, the only supported currency is USD.
    public var currencyCode: Ec2ClientTypes.CurrencyCodeValues?
    /// The purchase information of the Dedicated Host reservation and the Dedicated Hosts associated with it.
    public var purchase: [Ec2ClientTypes.Purchase]?
    /// The potential total hourly price of the reservation per hour.
    public var totalHourlyPrice: Swift.String?
    /// The potential total upfront price. This is billed immediately.
    public var totalUpfrontPrice: Swift.String?

    public init (
        currencyCode: Ec2ClientTypes.CurrencyCodeValues? = nil,
        purchase: [Ec2ClientTypes.Purchase]? = nil,
        totalHourlyPrice: Swift.String? = nil,
        totalUpfrontPrice: Swift.String? = nil
    )
    {
        self.currencyCode = currencyCode
        self.purchase = purchase
        self.totalHourlyPrice = totalHourlyPrice
        self.totalUpfrontPrice = totalUpfrontPrice
    }
}
