// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetNetworkInsightsAccessScopeAnalysisFindingsInput: Swift.Equatable {
    /// Checks whether you have the required permissions for the action, without actually making the request, and provides an error response. If you have the required permissions, the error response is DryRunOperation. Otherwise, it is UnauthorizedOperation.
    public var dryRun: Swift.Bool?
    /// The maximum number of results to return with a single call. To retrieve the remaining results, make another call with the returned nextToken value.
    public var maxResults: Swift.Int?
    /// The ID of the Network Access Scope analysis.
    /// This member is required.
    public var networkInsightsAccessScopeAnalysisId: Swift.String?
    /// The token for the next page of results.
    public var nextToken: Swift.String?

    public init (
        dryRun: Swift.Bool? = nil,
        maxResults: Swift.Int? = nil,
        networkInsightsAccessScopeAnalysisId: Swift.String? = nil,
        nextToken: Swift.String? = nil
    )
    {
        self.dryRun = dryRun
        self.maxResults = maxResults
        self.networkInsightsAccessScopeAnalysisId = networkInsightsAccessScopeAnalysisId
        self.nextToken = nextToken
    }
}
