// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetVpnConnectionDeviceSampleConfigurationOutputResponseBody: Swift.Equatable {
    let vpnConnectionDeviceSampleConfiguration: Swift.String?
}

extension GetVpnConnectionDeviceSampleConfigurationOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case vpnConnectionDeviceSampleConfiguration = "vpnConnectionDeviceSampleConfiguration"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let vpnConnectionDeviceSampleConfigurationDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .vpnConnectionDeviceSampleConfiguration)
        vpnConnectionDeviceSampleConfiguration = vpnConnectionDeviceSampleConfigurationDecoded
    }
}
