// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ProvisionByoipCidrOutputResponse: Swift.Equatable {
    /// Information about the address range.
    public var byoipCidr: EC2ClientTypes.ByoipCidr?

    public init (
        byoipCidr: EC2ClientTypes.ByoipCidr? = nil
    )
    {
        self.byoipCidr = byoipCidr
    }
}
