// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct RejectTransitGatewayPeeringAttachmentOutputResponseBody: Swift.Equatable {
    let transitGatewayPeeringAttachment: Ec2ClientTypes.TransitGatewayPeeringAttachment?
}

extension RejectTransitGatewayPeeringAttachmentOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case transitGatewayPeeringAttachment = "transitGatewayPeeringAttachment"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let transitGatewayPeeringAttachmentDecoded = try containerValues.decodeIfPresent(Ec2ClientTypes.TransitGatewayPeeringAttachment.self, forKey: .transitGatewayPeeringAttachment)
        transitGatewayPeeringAttachment = transitGatewayPeeringAttachmentDecoded
    }
}
