// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ReleaseAddressInputBody: Swift.Equatable {
    let allocationId: Swift.String?
    let publicIp: Swift.String?
    let networkBorderGroup: Swift.String?
    let dryRun: Swift.Bool?
}

extension ReleaseAddressInputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case allocationId = "AllocationId"
        case dryRun = "dryRun"
        case networkBorderGroup = "NetworkBorderGroup"
        case publicIp = "PublicIp"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let allocationIdDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .allocationId)
        allocationId = allocationIdDecoded
        let publicIpDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .publicIp)
        publicIp = publicIpDecoded
        let networkBorderGroupDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .networkBorderGroup)
        networkBorderGroup = networkBorderGroupDecoded
        let dryRunDecoded = try containerValues.decodeIfPresent(Swift.Bool.self, forKey: .dryRun)
        dryRun = dryRunDecoded
    }
}
