// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct StartNetworkInsightsAnalysisOutputResponse: Swift.Equatable {
    /// Information about the network insights analysis.
    public var networkInsightsAnalysis: Ec2ClientTypes.NetworkInsightsAnalysis?

    public init (
        networkInsightsAnalysis: Ec2ClientTypes.NetworkInsightsAnalysis? = nil
    )
    {
        self.networkInsightsAnalysis = networkInsightsAnalysis
    }
}
