// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension Ec2ClientTypes {
    /// Describes the state of a CIDR block.
    public struct SubnetCidrBlockState: Swift.Equatable {
        /// The state of a CIDR block.
        public var state: Ec2ClientTypes.SubnetCidrBlockStateCode?
        /// A message about the status of the CIDR block, if applicable.
        public var statusMessage: Swift.String?

        public init (
            state: Ec2ClientTypes.SubnetCidrBlockStateCode? = nil,
            statusMessage: Swift.String? = nil
        )
        {
            self.state = state
            self.statusMessage = statusMessage
        }
    }

}
