// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct CreateLocationFsxLustreOutputResponse: Swift.Equatable {
    /// The Amazon Resource Name (ARN) of the FSx for Lustre file system location that's created.
    public var locationArn: Swift.String?

    public init (
        locationArn: Swift.String? = nil
    )
    {
        self.locationArn = locationArn
    }
}
