// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// DescribeAgent
public struct DescribeAgentInput: Swift.Equatable {
    /// The Amazon Resource Name (ARN) of the agent to describe.
    /// This member is required.
    public var agentArn: Swift.String?

    public init (
        agentArn: Swift.String? = nil
    )
    {
        self.agentArn = agentArn
    }
}
