// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension KafkaClientTypes.ServerlessSasl: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case iam = "iam"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let iam = self.iam {
            try encodeContainer.encode(iam, forKey: .iam)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let iamDecoded = try containerValues.decodeIfPresent(KafkaClientTypes.Iam.self, forKey: .iam)
        iam = iamDecoded
    }
}
