// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Represents the input of a get blob operation.
public struct GetBlobInput: Swift.Equatable {
    /// The ID of the blob, which is its SHA-1 pointer.
    /// This member is required.
    public var blobId: Swift.String?
    /// The name of the repository that contains the blob.
    /// This member is required.
    public var repositoryName: Swift.String?

    public init (
        blobId: Swift.String? = nil,
        repositoryName: Swift.String? = nil
    )
    {
        self.blobId = blobId
        self.repositoryName = repositoryName
    }
}
