// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Represents the output of a put repository triggers operation.
public struct PutRepositoryTriggersOutputResponse: Swift.Equatable {
    /// The system-generated unique ID for the create or update operation.
    public var configurationId: Swift.String?

    public init (
        configurationId: Swift.String? = nil
    )
    {
        self.configurationId = configurationId
    }
}
