// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension Inspector2ClientTypes {
    /// The details that define an aggregation based on Amazon EC2 instances.
    public struct Ec2InstanceAggregation: Swift.Equatable {
        /// The AMI IDs associated with the Amazon EC2 instances to aggregate findings for.
        public var amis: [Inspector2ClientTypes.StringFilter]?
        /// The Amazon EC2 instance IDs to aggregate findings for.
        public var instanceIds: [Inspector2ClientTypes.StringFilter]?
        /// The Amazon EC2 instance tags to aggregate findings for.
        public var instanceTags: [Inspector2ClientTypes.MapFilter]?
        /// The operating system types to aggregate findings for. Valid values must be uppercase and underscore separated, examples are ORACLE_LINUX_7 and ALPINE_LINUX_3_8.
        public var operatingSystems: [Inspector2ClientTypes.StringFilter]?
        /// The value to sort results by.
        public var sortBy: Inspector2ClientTypes.Ec2InstanceSortBy?
        /// The order to sort results by.
        public var sortOrder: Inspector2ClientTypes.SortOrder?

        public init (
            amis: [Inspector2ClientTypes.StringFilter]? = nil,
            instanceIds: [Inspector2ClientTypes.StringFilter]? = nil,
            instanceTags: [Inspector2ClientTypes.MapFilter]? = nil,
            operatingSystems: [Inspector2ClientTypes.StringFilter]? = nil,
            sortBy: Inspector2ClientTypes.Ec2InstanceSortBy? = nil,
            sortOrder: Inspector2ClientTypes.SortOrder? = nil
        )
        {
            self.amis = amis
            self.instanceIds = instanceIds
            self.instanceTags = instanceTags
            self.operatingSystems = operatingSystems
            self.sortBy = sortBy
            self.sortOrder = sortOrder
        }
    }

}
