// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetIncidentRecordOutputResponse: ClientRuntime.HttpResponseBinding {
    public init (httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) throws {
        if case .stream(let reader) = httpResponse.body,
            let responseDecoder = decoder {
            let data = reader.toBytes().toData()
            let output: GetIncidentRecordOutputResponseBody = try responseDecoder.decode(responseBody: data)
            self.incidentRecord = output.incidentRecord
        } else {
            self.incidentRecord = nil
        }
    }
}
