// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime
import ClientRuntime

/// Request would cause a service quota to be exceeded.
public struct ServiceQuotaExceededException: AWSClientRuntime.AWSHttpServiceError, Swift.Equatable {
    public var _headers: ClientRuntime.Headers?
    public var _statusCode: ClientRuntime.HttpStatusCode?
    public var _message: Swift.String?
    public var _requestID: Swift.String?
    public var _retryable: Swift.Bool = false
    public var _isThrottling: Swift.Bool = false
    public var _type: ClientRuntime.ErrorType = .client
    /// This member is required.
    public var message: Swift.String?
    /// Originating quota code
    /// This member is required.
    public var quotaCode: Swift.String?
    /// The identifier for the requested resource
    public var resourceIdentifier: Swift.String?
    /// The resource type
    public var resourceType: SsmIncidentsClientTypes.ResourceType?
    /// Originating service code
    /// This member is required.
    public var serviceCode: SsmIncidentsClientTypes.ServiceCode?

    public init (
        message: Swift.String? = nil,
        quotaCode: Swift.String? = nil,
        resourceIdentifier: Swift.String? = nil,
        resourceType: SsmIncidentsClientTypes.ResourceType? = nil,
        serviceCode: SsmIncidentsClientTypes.ServiceCode? = nil
    )
    {
        self.message = message
        self.quotaCode = quotaCode
        self.resourceIdentifier = resourceIdentifier
        self.resourceType = resourceType
        self.serviceCode = serviceCode
    }
}
