// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime

public enum BatchGetDeploymentInstancesOutputError: Swift.Error, Swift.Equatable {
    case batchLimitExceededException(BatchLimitExceededException)
    case deploymentDoesNotExistException(DeploymentDoesNotExistException)
    case deploymentIdRequiredException(DeploymentIdRequiredException)
    case instanceIdRequiredException(InstanceIdRequiredException)
    case invalidComputePlatformException(InvalidComputePlatformException)
    case invalidDeploymentIdException(InvalidDeploymentIdException)
    case invalidInstanceNameException(InvalidInstanceNameException)
    case unknown(UnknownAWSHttpServiceError)
}
