// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct PutLifecycleEventHookExecutionStatusInputBody: Swift.Equatable {
    let deploymentId: Swift.String?
    let lifecycleEventHookExecutionId: Swift.String?
    let status: CodeDeployClientTypes.LifecycleEventStatus?
}

extension PutLifecycleEventHookExecutionStatusInputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case deploymentId
        case lifecycleEventHookExecutionId
        case status
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let deploymentIdDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .deploymentId)
        deploymentId = deploymentIdDecoded
        let lifecycleEventHookExecutionIdDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .lifecycleEventHookExecutionId)
        lifecycleEventHookExecutionId = lifecycleEventHookExecutionIdDecoded
        let statusDecoded = try containerValues.decodeIfPresent(CodeDeployClientTypes.LifecycleEventStatus.self, forKey: .status)
        status = statusDecoded
    }
}
