// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Represents the input of a StopDeployment operation.
public struct StopDeploymentInput: Swift.Equatable {
    /// Indicates, when a deployment is stopped, whether instances that have been updated should be rolled back to the previous version of the application revision.
    public var autoRollbackEnabled: Swift.Bool?
    /// The unique ID of a deployment.
    /// This member is required.
    public var deploymentId: Swift.String?

    public init (
        autoRollbackEnabled: Swift.Bool? = nil,
        deploymentId: Swift.String? = nil
    )
    {
        self.autoRollbackEnabled = autoRollbackEnabled
        self.deploymentId = deploymentId
    }
}
