// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DisassociateUserSettingsInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        guard let portalArn = portalArn else {
            return nil
        }
        return "/portals/\(portalArn)/userSettings"
    }
}
