// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ListRoutingControlsInput: Swift.Equatable {
    /// The Amazon Resource Name (ARN) of the control panel.
    /// This member is required.
    public var controlPanelArn: Swift.String?
    /// The number of objects that you want to return with this call.
    public var maxResults: Swift.Int
    /// The token that identifies which batch of results you want to see.
    public var nextToken: Swift.String?

    public init (
        controlPanelArn: Swift.String? = nil,
        maxResults: Swift.Int = 0,
        nextToken: Swift.String? = nil
    )
    {
        self.controlPanelArn = controlPanelArn
        self.maxResults = maxResults
        self.nextToken = nextToken
    }
}
