// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension Route53RecoveryControlConfigClientTypes {
    /// A routing control has one of two states: ON and OFF. You can map the routing control state to the state of an Amazon Route 53 health check, which can be used to control traffic routing.
    public struct RoutingControl: Swift.Equatable {
        /// The Amazon Resource Name (ARN) of the control panel that includes the routing control.
        public var controlPanelArn: Swift.String?
        /// The name of the routing control.
        public var name: Swift.String?
        /// The Amazon Resource Name (ARN) of the routing control.
        public var routingControlArn: Swift.String?
        /// The deployment status of a routing control. Status can be one of the following: PENDING, DEPLOYED, PENDING_DELETION.
        public var status: Route53RecoveryControlConfigClientTypes.Status?

        public init (
            controlPanelArn: Swift.String? = nil,
            name: Swift.String? = nil,
            routingControlArn: Swift.String? = nil,
            status: Route53RecoveryControlConfigClientTypes.Status? = nil
        )
        {
            self.controlPanelArn = controlPanelArn
            self.name = name
            self.routingControlArn = routingControlArn
            self.status = status
        }
    }

}
