// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SfnClientTypes.LambdaFunctionScheduleFailedEventDetails: Swift.CustomDebugStringConvertible {
    public var debugDescription: Swift.String {
        "LambdaFunctionScheduleFailedEventDetails(cause: \"CONTENT_REDACTED\", error: \"CONTENT_REDACTED\")"}
}
