// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteAccountAliasInput: Swift.Equatable {
    /// The name of the account alias to delete. This parameter allows (through its [regex pattern](http://wikipedia.org/wiki/regex)) a string of characters consisting of lowercase letters, digits, and dashes. You cannot start or finish with a dash, nor can you have two dashes in a row.
    /// This member is required.
    public var accountAlias: Swift.String?

    public init (
        accountAlias: Swift.String? = nil
    )
    {
        self.accountAlias = accountAlias
    }
}
