// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ListAccessKeysOutputResponse: ClientRuntime.HttpResponseBinding {
    public init (httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) throws {
        if case .stream(let reader) = httpResponse.body,
            let responseDecoder = decoder {
            let data = reader.toBytes().toData()
            let output: ListAccessKeysOutputResponseBody = try responseDecoder.decode(responseBody: data)
            self.accessKeyMetadata = output.accessKeyMetadata
            self.isTruncated = output.isTruncated
            self.marker = output.marker
        } else {
            self.accessKeyMetadata = nil
            self.isTruncated = false
            self.marker = nil
        }
    }
}
