// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListMFADevicesOutputResponseBody: Swift.Equatable {
    let mFADevices: [IamClientTypes.MFADevice]?
    let isTruncated: Swift.Bool
    let marker: Swift.String?
}

extension ListMFADevicesOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case isTruncated = "IsTruncated"
        case mFADevices = "MFADevices"
        case marker = "Marker"
    }

    public init (from decoder: Swift.Decoder) throws {
        let topLevelContainer = try decoder.container(keyedBy: ClientRuntime.Key.self)
        let containerValues = try topLevelContainer.nestedContainer(keyedBy: CodingKeys.self, forKey: ClientRuntime.Key("ListMFADevicesResult"))
        if containerValues.contains(.mFADevices) {
            struct KeyVal0{struct member{}}
            let mFADevicesWrappedContainer = containerValues.nestedContainerNonThrowable(keyedBy: CollectionMemberCodingKey<KeyVal0.member>.CodingKeys.self, forKey: .mFADevices)
            if let mFADevicesWrappedContainer = mFADevicesWrappedContainer {
                let mFADevicesContainer = try mFADevicesWrappedContainer.decodeIfPresent([IamClientTypes.MFADevice].self, forKey: .member)
                var mFADevicesBuffer:[IamClientTypes.MFADevice]? = nil
                if let mFADevicesContainer = mFADevicesContainer {
                    mFADevicesBuffer = [IamClientTypes.MFADevice]()
                    for structureContainer0 in mFADevicesContainer {
                        mFADevicesBuffer?.append(structureContainer0)
                    }
                }
                mFADevices = mFADevicesBuffer
            } else {
                mFADevices = []
            }
        } else {
            mFADevices = nil
        }
        let isTruncatedDecoded = try containerValues.decode(Swift.Bool.self, forKey: .isTruncated)
        isTruncated = isTruncatedDecoded
        let markerDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .marker)
        marker = markerDecoded
    }
}
