// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Gets the device response, as an administrator.
public struct AdminGetDeviceOutputResponse: Swift.Equatable {
    /// The device.
    /// This member is required.
    public var device: CognitoIdentityProviderClientTypes.DeviceType?

    public init (
        device: CognitoIdentityProviderClientTypes.DeviceType? = nil
    )
    {
        self.device = device
    }
}
