// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct EnableDomainAutoRenewInputBody: Swift.Equatable {
    let domainName: Swift.String?
}

extension EnableDomainAutoRenewInputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case domainName = "DomainName"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let domainNameDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .domainName)
        domainName = domainNameDecoded
    }
}
