// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetJobRunOutputResponse: Swift.Equatable {
    /// The output displays information about the job run.
    /// This member is required.
    public var jobRun: EmrServerlessClientTypes.JobRun?

    public init (
        jobRun: EmrServerlessClientTypes.JobRun? = nil
    )
    {
        self.jobRun = jobRun
    }
}
