// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime

public enum UpdateCustomKeyStoreOutputError: Swift.Error, Swift.Equatable {
    case cloudHsmClusterInvalidConfigurationException(CloudHsmClusterInvalidConfigurationException)
    case cloudHsmClusterNotActiveException(CloudHsmClusterNotActiveException)
    case cloudHsmClusterNotFoundException(CloudHsmClusterNotFoundException)
    case cloudHsmClusterNotRelatedException(CloudHsmClusterNotRelatedException)
    case customKeyStoreInvalidStateException(CustomKeyStoreInvalidStateException)
    case customKeyStoreNameInUseException(CustomKeyStoreNameInUseException)
    case customKeyStoreNotFoundException(CustomKeyStoreNotFoundException)
    case kMSInternalException(KMSInternalException)
    case unknown(UnknownAWSHttpServiceError)
}
