// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Configuration parameters used to create a new HarvestJob.
public struct CreateHarvestJobInput: Swift.Equatable {
    /// The end of the time-window which will be harvested
    /// This member is required.
    public var endTime: Swift.String?
    /// The ID of the HarvestJob. The ID must be unique within the region and it cannot be changed after the HarvestJob is submitted
    /// This member is required.
    public var id: Swift.String?
    /// The ID of the OriginEndpoint that the HarvestJob will harvest from. This cannot be changed after the HarvestJob is submitted.
    /// This member is required.
    public var originEndpointId: Swift.String?
    /// Configuration parameters for where in an S3 bucket to place the harvested content
    /// This member is required.
    public var s3Destination: MediaPackageClientTypes.S3Destination?
    /// The start of the time-window which will be harvested
    /// This member is required.
    public var startTime: Swift.String?

    public init (
        endTime: Swift.String? = nil,
        id: Swift.String? = nil,
        originEndpointId: Swift.String? = nil,
        s3Destination: MediaPackageClientTypes.S3Destination? = nil,
        startTime: Swift.String? = nil
    )
    {
        self.endTime = endTime
        self.id = id
        self.originEndpointId = originEndpointId
        self.s3Destination = s3Destination
        self.startTime = startTime
    }
}
