// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension DevOpsGuruClientTypes {
    /// A filter used by ListInsights to specify which insights to return.
    public struct ListInsightsStatusFilter: Swift.Equatable {
        /// A ListInsightsAnyStatusFilter that specifies insights of any status that are either REACTIVE or PROACTIVE.
        public var any: DevOpsGuruClientTypes.ListInsightsAnyStatusFilter?
        /// A ListInsightsClosedStatusFilter that specifies closed insights that are either REACTIVE or PROACTIVE.
        public var closed: DevOpsGuruClientTypes.ListInsightsClosedStatusFilter?
        /// A ListInsightsAnyStatusFilter that specifies ongoing insights that are either REACTIVE or PROACTIVE.
        public var ongoing: DevOpsGuruClientTypes.ListInsightsOngoingStatusFilter?

        public init (
            any: DevOpsGuruClientTypes.ListInsightsAnyStatusFilter? = nil,
            closed: DevOpsGuruClientTypes.ListInsightsClosedStatusFilter? = nil,
            ongoing: DevOpsGuruClientTypes.ListInsightsOngoingStatusFilter? = nil
        )
        {
            self.any = any
            self.closed = closed
            self.ongoing = ongoing
        }
    }

}
