// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DescribeClientPropertiesInput: Swift.Equatable {
    /// The resource identifier, in the form of directory IDs.
    /// This member is required.
    public var resourceIds: [Swift.String]?

    public init (
        resourceIds: [Swift.String]? = nil
    )
    {
        self.resourceIds = resourceIds
    }
}
