// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetCodeSigningConfigOutputResponseBody: Swift.Equatable {
    let codeSigningConfig: LambdaClientTypes.CodeSigningConfig?
}

extension GetCodeSigningConfigOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case codeSigningConfig = "CodeSigningConfig"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let codeSigningConfigDecoded = try containerValues.decodeIfPresent(LambdaClientTypes.CodeSigningConfig.self, forKey: .codeSigningConfig)
        codeSigningConfig = codeSigningConfigDecoded
    }
}
