// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct PutTraceSegmentsInput: Swift.Equatable {
    /// A string containing a JSON document defining one or more segments or subsegments.
    /// This member is required.
    public var traceSegmentDocuments: [Swift.String]?

    public init (
        traceSegmentDocuments: [Swift.String]? = nil
    )
    {
        self.traceSegmentDocuments = traceSegmentDocuments
    }
}
