// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteVirtualInterfaceInput: Swift.Equatable {
    /// The ID of the virtual interface.
    /// This member is required.
    public var virtualInterfaceId: Swift.String?

    public init (
        virtualInterfaceId: Swift.String? = nil
    )
    {
        self.virtualInterfaceId = virtualInterfaceId
    }
}
