// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension AddTagsOutputResponse: ClientRuntime.HttpResponseBinding {
    public init (httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) throws {
        if case .stream(let reader) = httpResponse.body,
            let responseDecoder = decoder {
            let data = reader.toBytes().toData()
            let output: AddTagsOutputResponseBody = try responseDecoder.decode(responseBody: data)
            self.resourceId = output.resourceId
            self.resourceType = output.resourceType
        } else {
            self.resourceId = nil
            self.resourceType = nil
        }
    }
}
