// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetTransitGatewayPeeringInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        guard let peeringId = peeringId else {
            return nil
        }
        return "/transit-gateway-peerings/\(peeringId.urlPercentEncoding())"
    }
}
