// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ListOrganizationServiceAccessStatusInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        return "/organizations/service-access"
    }
}
