// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetUserInputBody: Swift.Equatable {
}

extension GetUserInputBody: Swift.Decodable {

    public init (from decoder: Swift.Decoder) throws {
    }
}
