// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension OpsWorksClientTypes {
    /// The Shutdown event configuration.
    public struct ShutdownEventConfiguration: Swift.Equatable {
        /// Whether to enable Elastic Load Balancing connection draining. For more information, see [Connection Draining](https://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/TerminologyandKeyConcepts.html#conn-drain)
        public var delayUntilElbConnectionsDrained: Swift.Bool?
        /// The time, in seconds, that AWS OpsWorks Stacks will wait after triggering a Shutdown event before shutting down an instance.
        public var executionTimeout: Swift.Int?

        public init (
            delayUntilElbConnectionsDrained: Swift.Bool? = nil,
            executionTimeout: Swift.Int? = nil
        )
        {
            self.delayUntilElbConnectionsDrained = delayUntilElbConnectionsDrained
            self.executionTimeout = executionTimeout
        }
    }

}
