// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct AssociateResourceInput: Swift.Equatable {
    /// Specifies the group. You can specify the group name, the ARN, or the group ID as the GroupIdentifier.
    /// This member is required.
    public var groupIdentifier: Swift.String?
    /// The ARN of the canary that you want to associate with the specified group.
    /// This member is required.
    public var resourceArn: Swift.String?

    public init (
        groupIdentifier: Swift.String? = nil,
        resourceArn: Swift.String? = nil
    )
    {
        self.groupIdentifier = groupIdentifier
        self.resourceArn = resourceArn
    }
}
