// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DeleteSlotInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        guard let botId = botId else {
            return nil
        }
        guard let botVersion = botVersion else {
            return nil
        }
        guard let localeId = localeId else {
            return nil
        }
        guard let intentId = intentId else {
            return nil
        }
        guard let slotId = slotId else {
            return nil
        }
        return "/bots/\(botId.urlPercentEncoding())/botversions/\(botVersion.urlPercentEncoding())/botlocales/\(localeId.urlPercentEncoding())/intents/\(intentId.urlPercentEncoding())/slots/\(slotId.urlPercentEncoding())"
    }
}
