// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct CreateCostCategoryDefinitionOutputResponse: Swift.Equatable {
    /// The unique identifier for your newly created Cost Category.
    public var costCategoryArn: Swift.String?
    /// The Cost Category's effective start date. It can only be a billing start date (first day of the month).
    public var effectiveStart: Swift.String?

    public init (
        costCategoryArn: Swift.String? = nil,
        effectiveStart: Swift.String? = nil
    )
    {
        self.costCategoryArn = costCategoryArn
        self.effectiveStart = effectiveStart
    }
}
