// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteTableInput: Swift.Equatable {
    /// The name of the keyspace of the to be deleted table.
    /// This member is required.
    public var keyspaceName: Swift.String?
    /// The name of the table to be deleted.
    /// This member is required.
    public var tableName: Swift.String?

    public init (
        keyspaceName: Swift.String? = nil,
        tableName: Swift.String? = nil
    )
    {
        self.keyspaceName = keyspaceName
        self.tableName = tableName
    }
}
