// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension LexModelBuildingClientTypes {
    /// Provides information about a built in slot type.
    public struct BuiltinSlotTypeMetadata: Swift.Equatable {
        /// A unique identifier for the built-in slot type. To find the signature for a slot type, see [Slot Type Reference](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference) in the Alexa Skills Kit.
        public var signature: Swift.String?
        /// A list of target locales for the slot.
        public var supportedLocales: [LexModelBuildingClientTypes.Locale]?

        public init (
            signature: Swift.String? = nil,
            supportedLocales: [LexModelBuildingClientTypes.Locale]? = nil
        )
        {
            self.signature = signature
            self.supportedLocales = supportedLocales
        }
    }

}
