// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension LexModelBuildingClientTypes {
    public enum ExportType: Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Codable, Swift.Hashable {
        case alexaSkillsKit
        case lex
        case sdkUnknown(Swift.String)

        public static var allCases: [ExportType] {
            return [
                .alexaSkillsKit,
                .lex,
                .sdkUnknown("")
            ]
        }
        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }
        public var rawValue: Swift.String {
            switch self {
            case .alexaSkillsKit: return "ALEXA_SKILLS_KIT"
            case .lex: return "LEX"
            case let .sdkUnknown(s): return s
            }
        }
        public init(from decoder: Swift.Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(RawValue.self)
            self = ExportType(rawValue: rawValue) ?? ExportType.sdkUnknown(rawValue)
        }
    }
}
