// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetBotVersionsInput: Swift.Equatable {
    /// The maximum number of bot versions to return in the response. The default is 10.
    public var maxResults: Swift.Int?
    /// The name of the bot for which versions should be returned.
    /// This member is required.
    public var name: Swift.String?
    /// A pagination token for fetching the next page of bot versions. If the response to this call is truncated, Amazon Lex returns a pagination token in the response. To fetch the next page of versions, specify the pagination token in the next request.
    public var nextToken: Swift.String?

    public init (
        maxResults: Swift.Int? = nil,
        name: Swift.String? = nil,
        nextToken: Swift.String? = nil
    )
    {
        self.maxResults = maxResults
        self.name = name
        self.nextToken = nextToken
    }
}
