// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension UpdateBackendJobOutputResponse: ClientRuntime.HttpResponseBinding {
    public init (httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) throws {
        if case .stream(let reader) = httpResponse.body,
            let responseDecoder = decoder {
            let data = reader.toBytes().toData()
            let output: UpdateBackendJobOutputResponseBody = try responseDecoder.decode(responseBody: data)
            self.appId = output.appId
            self.backendEnvironmentName = output.backendEnvironmentName
            self.createTime = output.createTime
            self.error = output.error
            self.jobId = output.jobId
            self.operation = output.operation
            self.status = output.status
            self.updateTime = output.updateTime
        } else {
            self.appId = nil
            self.backendEnvironmentName = nil
            self.createTime = nil
            self.error = nil
            self.jobId = nil
            self.operation = nil
            self.status = nil
            self.updateTime = nil
        }
    }
}
