// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct DeleteWirelessGatewayTaskDefinitionInputBody: Swift.Equatable {
}

extension DeleteWirelessGatewayTaskDefinitionInputBody: Swift.Decodable {

    public init (from decoder: Swift.Decoder) throws {
    }
}
