// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetChannelOutputResponseBody: Swift.Equatable {
    let channel: IvsClientTypes.Channel?
}

extension GetChannelOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case channel
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let channelDecoded = try containerValues.decodeIfPresent(IvsClientTypes.Channel.self, forKey: .channel)
        channel = channelDecoded
    }
}
