// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension AmplifyUiBuilderClientTypes {
    /// A key-value pair that defines a property of a theme.
    public struct ThemeValues: Swift.Equatable {
        /// The name of the property.
        public var key: Swift.String?
        /// The value of the property.
        public var value: AmplifyUiBuilderClientTypes.ThemeValue?

        public init (
            key: Swift.String? = nil,
            value: AmplifyUiBuilderClientTypes.ThemeValue? = nil
        )
        {
            self.key = key
            self.value = value
        }
    }

}
