// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct UpdateComponentInputBodyMiddleware: ClientRuntime.Middleware {
    public let id: Swift.String = "UpdateComponentInputBodyMiddleware"

    public init() {}

    public func handle<H>(context: Context,
                  input: ClientRuntime.SerializeStepInput<UpdateComponentInput>,
                  next: H) async throws -> ClientRuntime.OperationOutput<UpdateComponentOutputResponse>
    where H: Handler,
    Self.MInput == H.Input,
    Self.MOutput == H.Output,
    Self.Context == H.Context
    {
        do {
            let encoder = context.getEncoder()
            if let updatedComponent = input.operationInput.updatedComponent {
                let updatedComponentdata = try encoder.encode(updatedComponent)
                let updatedComponentbody = ClientRuntime.HttpBody.data(updatedComponentdata)
                input.builder.withBody(updatedComponentbody)
            } else {
                let updatedComponentdata = try encoder.encode(input.operationInput)
                let updatedComponentbody = ClientRuntime.HttpBody.data(updatedComponentdata)
                input.builder.withBody(updatedComponentbody)
            }
        } catch let err {
            throw SdkError<UpdateComponentOutputError>.client(ClientRuntime.ClientError.serializationFailed(err.localizedDescription))
        }
        return try await next.handle(context: context, input: input)
    }

    public typealias MInput = ClientRuntime.SerializeStepInput<UpdateComponentInput>
    public typealias MOutput = ClientRuntime.OperationOutput<UpdateComponentOutputResponse>
    public typealias Context = ClientRuntime.HttpContext
}
