// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// The result of a DeleteAnalysisScheme request. Contains the status of the deleted analysis scheme.
public struct DeleteAnalysisSchemeOutputResponse: Swift.Equatable {
    /// The status of the analysis scheme being deleted.
    /// This member is required.
    public var analysisScheme: CloudSearchClientTypes.AnalysisSchemeStatus?

    public init (
        analysisScheme: CloudSearchClientTypes.AnalysisSchemeStatus? = nil
    )
    {
        self.analysisScheme = analysisScheme
    }
}
