// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension InspectorClientTypes {
    /// This data type contains key-value pairs that identify various Amazon resources.
    public struct Scope: Swift.Equatable {
        /// The type of the scope.
        public var key: InspectorClientTypes.ScopeType?
        /// The resource identifier for the specified scope type.
        public var value: Swift.String?

        public init (
            key: InspectorClientTypes.ScopeType? = nil,
            value: Swift.String? = nil
        )
        {
            self.key = key
            self.value = value
        }
    }

}
