// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime

public enum AcceptAdministratorInvitationOutputError: Swift.Error, Swift.Equatable {
    case badRequestException(BadRequestException)
    case internalServerErrorException(InternalServerErrorException)
    case unknown(UnknownAWSHttpServiceError)
}
