// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DescribePullThroughCacheRulesInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case ecrRepositoryPrefixes
        case maxResults
        case nextToken
        case registryId
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let ecrRepositoryPrefixes = ecrRepositoryPrefixes {
            var ecrRepositoryPrefixesContainer = encodeContainer.nestedUnkeyedContainer(forKey: .ecrRepositoryPrefixes)
            for pullthroughcacherulerepositoryprefixlist0 in ecrRepositoryPrefixes {
                try ecrRepositoryPrefixesContainer.encode(pullthroughcacherulerepositoryprefixlist0)
            }
        }
        if let maxResults = self.maxResults {
            try encodeContainer.encode(maxResults, forKey: .maxResults)
        }
        if let nextToken = self.nextToken {
            try encodeContainer.encode(nextToken, forKey: .nextToken)
        }
        if let registryId = self.registryId {
            try encodeContainer.encode(registryId, forKey: .registryId)
        }
    }
}
