// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension ConfigClientTypes {
    /// The number of conformance packs that are compliant and noncompliant.
    public struct AggregateConformancePackComplianceCount: Swift.Equatable {
        /// Number of compliant conformance packs.
        public var compliantConformancePackCount: Swift.Int
        /// Number of noncompliant conformance packs.
        public var nonCompliantConformancePackCount: Swift.Int

        public init (
            compliantConformancePackCount: Swift.Int = 0,
            nonCompliantConformancePackCount: Swift.Int = 0
        )
        {
            self.compliantConformancePackCount = compliantConformancePackCount
            self.nonCompliantConformancePackCount = nonCompliantConformancePackCount
        }
    }

}
