// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime

public enum GetOrganizationCustomRulePolicyOutputError: Swift.Error, Swift.Equatable {
    case noSuchOrganizationConfigRuleException(NoSuchOrganizationConfigRuleException)
    case organizationAccessDeniedException(OrganizationAccessDeniedException)
    case unknown(UnknownAWSHttpServiceError)
}
