// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension TransferClientTypes {
    public enum ProfileType: Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Codable, Swift.Hashable {
        case local
        case partner
        case sdkUnknown(Swift.String)

        public static var allCases: [ProfileType] {
            return [
                .local,
                .partner,
                .sdkUnknown("")
            ]
        }
        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }
        public var rawValue: Swift.String {
            switch self {
            case .local: return "LOCAL"
            case .partner: return "PARTNER"
            case let .sdkUnknown(s): return s
            }
        }
        public init(from decoder: Swift.Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(RawValue.self)
            self = ProfileType(rawValue: rawValue) ?? ProfileType.sdkUnknown(rawValue)
        }
    }
}
