// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DeleteWebACLInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case changeToken = "ChangeToken"
        case webACLId = "WebACLId"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let changeToken = self.changeToken {
            try encodeContainer.encode(changeToken, forKey: .changeToken)
        }
        if let webACLId = self.webACLId {
            try encodeContainer.encode(webACLId, forKey: .webACLId)
        }
    }
}
