// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetRateBasedRuleManagedKeysInput: Swift.Equatable {
    /// A null value and not currently used. Do not include this in your request.
    public var nextMarker: Swift.String?
    /// The RuleId of the [RateBasedRule] for which you want to get a list of ManagedKeys. RuleId is returned by [CreateRateBasedRule] and by [ListRateBasedRules].
    /// This member is required.
    public var ruleId: Swift.String?

    public init (
        nextMarker: Swift.String? = nil,
        ruleId: Swift.String? = nil
    )
    {
        self.nextMarker = nextMarker
        self.ruleId = ruleId
    }
}
