// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension EmrClientTypes {
    public enum InstanceFleetState: Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Codable, Swift.Hashable {
        case bootstrapping
        case provisioning
        case resizing
        case running
        case suspended
        case terminated
        case terminating
        case sdkUnknown(Swift.String)

        public static var allCases: [InstanceFleetState] {
            return [
                .bootstrapping,
                .provisioning,
                .resizing,
                .running,
                .suspended,
                .terminated,
                .terminating,
                .sdkUnknown("")
            ]
        }
        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }
        public var rawValue: Swift.String {
            switch self {
            case .bootstrapping: return "BOOTSTRAPPING"
            case .provisioning: return "PROVISIONING"
            case .resizing: return "RESIZING"
            case .running: return "RUNNING"
            case .suspended: return "SUSPENDED"
            case .terminated: return "TERMINATED"
            case .terminating: return "TERMINATING"
            case let .sdkUnknown(s): return s
            }
        }
        public init(from decoder: Swift.Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(RawValue.self)
            self = InstanceFleetState(rawValue: rawValue) ?? InstanceFleetState.sdkUnknown(rawValue)
        }
    }
}
