// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteKeyPairInput: Swift.Equatable {
    /// The RSA fingerprint of the Lightsail default key pair to delete. The expectedFingerprint parameter is required only when specifying to delete a Lightsail default key pair.
    public var expectedFingerprint: Swift.String?
    /// The name of the key pair to delete.
    /// This member is required.
    public var keyPairName: Swift.String?

    public init (
        expectedFingerprint: Swift.String? = nil,
        keyPairName: Swift.String? = nil
    )
    {
        self.expectedFingerprint = expectedFingerprint
        self.keyPairName = keyPairName
    }
}
