// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteAlarmInput: Swift.Equatable {
    /// The name of the alarm to delete.
    /// This member is required.
    public var alarmName: Swift.String?

    public init (
        alarmName: Swift.String? = nil
    )
    {
        self.alarmName = alarmName
    }
}
