// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetLoadBalancerTlsPoliciesOutputResponse: Swift.Equatable {
    /// The token to advance to the next page of results from your request. A next page token is not returned if there are no more results to display. To get the next page of results, perform another GetLoadBalancerTlsPolicies request and specify the next page token using the pageToken parameter.
    public var nextPageToken: Swift.String?
    /// An array of objects that describe the TLS security policies that are available.
    public var tlsPolicies: [LightsailClientTypes.LoadBalancerTlsPolicy]?

    public init (
        nextPageToken: Swift.String? = nil,
        tlsPolicies: [LightsailClientTypes.LoadBalancerTlsPolicy]? = nil
    )
    {
        self.nextPageToken = nextPageToken
        self.tlsPolicies = tlsPolicies
    }
}
