// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UntagResourceInput: Swift.Equatable {
    /// The Amazon Resource Name (ARN) of the resource from which you want to remove a tag.
    public var resourceArn: Swift.String?
    /// The name of the resource from which you are removing a tag.
    /// This member is required.
    public var resourceName: Swift.String?
    /// The tag keys to delete from the specified resource.
    /// This member is required.
    public var tagKeys: [Swift.String]?

    public init (
        resourceArn: Swift.String? = nil,
        resourceName: Swift.String? = nil,
        tagKeys: [Swift.String]? = nil
    )
    {
        self.resourceArn = resourceArn
        self.resourceName = resourceName
        self.tagKeys = tagKeys
    }
}
