// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension RegisterDeviceInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case platform = "Platform"
        case token = "Token"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let platform = self.platform {
            try encodeContainer.encode(platform.rawValue, forKey: .platform)
        }
        if let token = self.token {
            try encodeContainer.encode(token, forKey: .token)
        }
    }
}
