// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension CreateNetworkInput: Swift.CustomDebugStringConvertible {
    public var debugDescription: Swift.String {
        "CreateNetworkInput(clientToken: \(Swift.String(describing: clientToken)), description: \(Swift.String(describing: description)), networkName: \(Swift.String(describing: networkName)), tags: \"CONTENT_REDACTED\")"}
}
