// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DescribeAlgorithmOutputResponse: Swift.Equatable {
    /// A listing of the properties of the algorithm.
    public var algorithm: PersonalizeClientTypes.Algorithm?

    public init (
        algorithm: PersonalizeClientTypes.Algorithm? = nil
    )
    {
        self.algorithm = algorithm
    }
}
