// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension BatchUpdateScheduleInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case creates = "creates"
        case deletes = "deletes"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let creates = self.creates {
            try encodeContainer.encode(creates, forKey: .creates)
        }
        if let deletes = self.deletes {
            try encodeContainer.encode(deletes, forKey: .deletes)
        }
    }
}
