// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension MediaLiveClientTypes {
    /// Resource type, 'INPUT', 'OUTPUT', 'MULTIPLEX', or 'CHANNEL'
    public enum ReservationResourceType: Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Codable, Swift.Hashable {
        case channel
        case input
        case multiplex
        case output
        case sdkUnknown(Swift.String)

        public static var allCases: [ReservationResourceType] {
            return [
                .channel,
                .input,
                .multiplex,
                .output,
                .sdkUnknown("")
            ]
        }
        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }
        public var rawValue: Swift.String {
            switch self {
            case .channel: return "CHANNEL"
            case .input: return "INPUT"
            case .multiplex: return "MULTIPLEX"
            case .output: return "OUTPUT"
            case let .sdkUnknown(s): return s
            }
        }
        public init(from decoder: Swift.Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(RawValue.self)
            self = ReservationResourceType(rawValue: rawValue) ?? ReservationResourceType.sdkUnknown(rawValue)
        }
    }
}
