// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension MediaLiveClientTypes.VideoSelectorProgramId: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case programId = "programId"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let programId = self.programId {
            try encodeContainer.encode(programId, forKey: .programId)
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let programIdDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .programId)
        programId = programIdDecoded
    }
}
