// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension ShieldClientTypes {
    /// Statistics objects for the various data types in [AttackVolume].
    public struct AttackVolumeStatistics: Swift.Equatable {
        /// The maximum attack volume observed for the given unit.
        /// This member is required.
        public var max: Swift.Double

        public init (
            max: Swift.Double = 0.0
        )
        {
            self.max = max
        }
    }

}
