// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct BatchGetWorkflowsOutputResponse: Swift.Equatable {
    /// A list of names of workflows not found.
    public var missingWorkflows: [Swift.String]?
    /// A list of workflow resource metadata.
    public var workflows: [GlueClientTypes.Workflow]?

    public init (
        missingWorkflows: [Swift.String]? = nil,
        workflows: [GlueClientTypes.Workflow]? = nil
    )
    {
        self.missingWorkflows = missingWorkflows
        self.workflows = workflows
    }
}
