// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension GlueClientTypes {
    /// The URIs for function resources.
    public struct ResourceUri: Swift.Equatable {
        /// The type of the resource.
        public var resourceType: GlueClientTypes.ResourceType?
        /// The URI for accessing the resource.
        public var uri: Swift.String?

        public init (
            resourceType: GlueClientTypes.ResourceType? = nil,
            uri: Swift.String? = nil
        )
        {
            self.resourceType = resourceType
            self.uri = uri
        }
    }

}
