// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct StartBlueprintRunInput: Swift.Equatable {
    /// The name of the blueprint.
    /// This member is required.
    public var blueprintName: Swift.String?
    /// Specifies the parameters as a BlueprintParameters object.
    public var parameters: Swift.String?
    /// Specifies the IAM role used to create the workflow.
    /// This member is required.
    public var roleArn: Swift.String?

    public init (
        blueprintName: Swift.String? = nil,
        parameters: Swift.String? = nil,
        roleArn: Swift.String? = nil
    )
    {
        self.blueprintName = blueprintName
        self.parameters = parameters
        self.roleArn = roleArn
    }
}
