// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateBlueprintOutputResponse: Swift.Equatable {
    /// Returns the name of the blueprint that was updated.
    public var name: Swift.String?

    public init (
        name: Swift.String? = nil
    )
    {
        self.name = name
    }
}
