// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct CloudHsmInternalExceptionBody: Swift.Equatable {
    let message: Swift.String?
    let retryable: Swift.Bool
}

extension CloudHsmInternalExceptionBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case message
        case retryable
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let messageDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .message)
        message = messageDecoded
        let retryableDecoded = try containerValues.decodeIfPresent(Swift.Bool.self, forKey: .retryable) ?? false
        retryable = retryableDecoded
    }
}
