// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DescribeConnectorInput: Swift.Equatable {
    /// The label of the connector. The label is unique for each ConnectorRegistration in your Amazon Web Services account. Only needed if calling for CUSTOMCONNECTOR connector type/.
    public var connectorLabel: Swift.String?
    /// The connector type, such as CUSTOMCONNECTOR, Saleforce, Marketo. Please choose CUSTOMCONNECTOR for Lambda based custom connectors.
    /// This member is required.
    public var connectorType: AppflowClientTypes.ConnectorType?

    public init (
        connectorLabel: Swift.String? = nil,
        connectorType: AppflowClientTypes.ConnectorType? = nil
    )
    {
        self.connectorLabel = connectorLabel
        self.connectorType = connectorType
    }
}
