// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListConnectorsOutputResponseBody: Swift.Equatable {
    let connectors: [AppflowClientTypes.ConnectorDetail]?
    let nextToken: Swift.String?
}

extension ListConnectorsOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case connectors
        case nextToken
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let connectorsContainer = try containerValues.decodeIfPresent([AppflowClientTypes.ConnectorDetail?].self, forKey: .connectors)
        var connectorsDecoded0:[AppflowClientTypes.ConnectorDetail]? = nil
        if let connectorsContainer = connectorsContainer {
            connectorsDecoded0 = [AppflowClientTypes.ConnectorDetail]()
            for structure0 in connectorsContainer {
                if let structure0 = structure0 {
                    connectorsDecoded0?.append(structure0)
                }
            }
        }
        connectors = connectorsDecoded0
        let nextTokenDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .nextToken)
        nextToken = nextTokenDecoded
    }
}
