// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension StopProductSubscriptionOutputResponse: ClientRuntime.HttpResponseBinding {
    public init (httpResponse: ClientRuntime.HttpResponse, decoder: ClientRuntime.ResponseDecoder? = nil) throws {
        if case .stream(let reader) = httpResponse.body,
            let responseDecoder = decoder {
            let data = reader.toBytes().toData()
            let output: StopProductSubscriptionOutputResponseBody = try responseDecoder.decode(responseBody: data)
            self.productUserSummary = output.productUserSummary
        } else {
            self.productUserSummary = nil
        }
    }
}
