// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension LakeFormationClientTypes {
    public enum OptimizerType: Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Codable, Swift.Hashable {
        case compaction
        case garbageCollection
        case generic
        case sdkUnknown(Swift.String)

        public static var allCases: [OptimizerType] {
            return [
                .compaction,
                .garbageCollection,
                .generic,
                .sdkUnknown("")
            ]
        }
        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }
        public var rawValue: Swift.String {
            switch self {
            case .compaction: return "COMPACTION"
            case .garbageCollection: return "GARBAGE_COLLECTION"
            case .generic: return "ALL"
            case let .sdkUnknown(s): return s
            }
        }
        public init(from decoder: Swift.Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(RawValue.self)
            self = OptimizerType(rawValue: rawValue) ?? OptimizerType.sdkUnknown(rawValue)
        }
    }
}
