// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListJournalKinesisStreamsForLedgerOutputResponseBody: Swift.Equatable {
    let streams: [QldbClientTypes.JournalKinesisStreamDescription]?
    let nextToken: Swift.String?
}

extension ListJournalKinesisStreamsForLedgerOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case nextToken = "NextToken"
        case streams = "Streams"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let streamsContainer = try containerValues.decodeIfPresent([QldbClientTypes.JournalKinesisStreamDescription?].self, forKey: .streams)
        var streamsDecoded0:[QldbClientTypes.JournalKinesisStreamDescription]? = nil
        if let streamsContainer = streamsContainer {
            streamsDecoded0 = [QldbClientTypes.JournalKinesisStreamDescription]()
            for structure0 in streamsContainer {
                if let structure0 = structure0 {
                    streamsDecoded0?.append(structure0)
                }
            }
        }
        streams = streamsDecoded0
        let nextTokenDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .nextToken)
        nextToken = nextTokenDecoded
    }
}
