// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct CopyDBParameterGroupOutputResponse: Swift.Equatable {
    /// Contains the details of an Amazon RDS DB parameter group. This data type is used as a response element in the DescribeDBParameterGroups action.
    public var dBParameterGroup: RdsClientTypes.DBParameterGroup?

    public init (
        dBParameterGroup: RdsClientTypes.DBParameterGroup? = nil
    )
    {
        self.dBParameterGroup = dBParameterGroup
    }
}
