// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension RdsClientTypes {
    public enum CustomEngineVersionStatus: Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Codable, Swift.Hashable {
        case available
        case inactive
        case inactiveExceptRestore
        case sdkUnknown(Swift.String)

        public static var allCases: [CustomEngineVersionStatus] {
            return [
                .available,
                .inactive,
                .inactiveExceptRestore,
                .sdkUnknown("")
            ]
        }
        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }
        public var rawValue: Swift.String {
            switch self {
            case .available: return "available"
            case .inactive: return "inactive"
            case .inactiveExceptRestore: return "inactive-except-restore"
            case let .sdkUnknown(s): return s
            }
        }
        public init(from decoder: Swift.Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(RawValue.self)
            self = CustomEngineVersionStatus(rawValue: rawValue) ?? CustomEngineVersionStatus.sdkUnknown(rawValue)
        }
    }
}
