// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DescribeScriptInput: Swift.Equatable {
    /// A unique identifier for the Realtime script to retrieve properties for. You can use either the script ID or ARN value.
    /// This member is required.
    public var scriptId: Swift.String?

    public init (
        scriptId: Swift.String? = nil
    )
    {
        self.scriptId = scriptId
    }
}
