// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime
import ClientRuntime

/// Requested display language code is not supported.
public struct UnsupportedDisplayLanguageCodeException: AWSClientRuntime.AWSHttpServiceError, Swift.Equatable {
    public var _headers: ClientRuntime.Headers?
    public var _statusCode: ClientRuntime.HttpStatusCode?
    public var _message: Swift.String?
    public var _requestID: Swift.String?
    public var _retryable: Swift.Bool = false
    public var _isThrottling: Swift.Bool = false
    public var _type: ClientRuntime.ErrorType = .client
    /// Language code passed in with the request.
    public var displayLanguageCode: Swift.String?
    public var message: Swift.String?

    public init (
        displayLanguageCode: Swift.String? = nil,
        message: Swift.String? = nil
    )
    {
        self.displayLanguageCode = displayLanguageCode
        self.message = message
    }
}
