// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct CreateTrackerOutputResponse: Swift.Equatable {
    /// The timestamp for when the tracker resource was created in [ ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format: YYYY-MM-DDThh:mm:ss.sssZ.
    /// This member is required.
    public var createTime: ClientRuntime.Date?
    /// The Amazon Resource Name (ARN) for the tracker resource. Used when you need to specify a resource across all AWS.
    ///
    /// * Format example: arn:aws:geo:region:account-id:tracker/ExampleTracker
    /// This member is required.
    public var trackerArn: Swift.String?
    /// The name of the tracker resource.
    /// This member is required.
    public var trackerName: Swift.String?

    public init (
        createTime: ClientRuntime.Date? = nil,
        trackerArn: Swift.String? = nil,
        trackerName: Swift.String? = nil
    )
    {
        self.createTime = createTime
        self.trackerArn = trackerArn
        self.trackerName = trackerName
    }
}
