// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ListPlaceIndexesInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        return "/places/v0/list-indexes"
    }
}
