// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension LocationClientTypes {
    /// The result for the calculated route of one DeparturePositionDestinationPosition pair.
    public struct RouteMatrixEntry: Swift.Equatable {
        /// The total distance of travel for the route.
        public var distance: Swift.Double?
        /// The expected duration of travel for the route.
        public var durationSeconds: Swift.Double?
        /// An error corresponding to the calculation of a route between the DeparturePosition and DestinationPosition.
        public var error: LocationClientTypes.RouteMatrixEntryError?

        public init (
            distance: Swift.Double? = nil,
            durationSeconds: Swift.Double? = nil,
            error: LocationClientTypes.RouteMatrixEntryError? = nil
        )
        {
            self.distance = distance
            self.durationSeconds = durationSeconds
            self.error = error
        }
    }

}
