// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListStudiosInputBody: Swift.Equatable {
}

extension ListStudiosInputBody: Swift.Decodable {

    public init (from decoder: Swift.Decoder) throws {
    }
}
