// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DeleteStreamInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        guard let streamId = streamId else {
            return nil
        }
        return "/streams/\(streamId.urlPercentEncoding())"
    }
}
