// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DescribeDomainConfigurationInput: Swift.Equatable {
    /// The name of the domain configuration.
    /// This member is required.
    public var domainConfigurationName: Swift.String?

    public init (
        domainConfigurationName: Swift.String? = nil
    )
    {
        self.domainConfigurationName = domainConfigurationName
    }
}
