// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetTopicRuleOutputResponseBody: Swift.Equatable {
    let ruleArn: Swift.String?
    let rule: IotClientTypes.TopicRule?
}

extension GetTopicRuleOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case rule
        case ruleArn
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let ruleArnDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .ruleArn)
        ruleArn = ruleArnDecoded
        let ruleDecoded = try containerValues.decodeIfPresent(IotClientTypes.TopicRule.self, forKey: .rule)
        rule = ruleDecoded
    }
}
