// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ListCustomMetricsOutputResponse: Swift.Equatable {
    /// The name of the custom metric.
    public var metricNames: [Swift.String]?
    /// A token that can be used to retrieve the next set of results, or null if there are no additional results.
    public var nextToken: Swift.String?

    public init (
        metricNames: [Swift.String]? = nil,
        nextToken: Swift.String? = nil
    )
    {
        self.metricNames = metricNames
        self.nextToken = nextToken
    }
}
