// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension RekognitionClientTypes {
    /// The stream processor settings that you want to update. ConnectedHome settings can be updated to detect different labels with a different minimum confidence.
    public struct StreamProcessorSettingsForUpdate: Swift.Equatable {
        /// The label detection settings you want to use for your stream processor.
        public var connectedHomeForUpdate: RekognitionClientTypes.ConnectedHomeSettingsForUpdate?

        public init (
            connectedHomeForUpdate: RekognitionClientTypes.ConnectedHomeSettingsForUpdate? = nil
        )
        {
            self.connectedHomeForUpdate = connectedHomeForUpdate
        }
    }

}
