// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct DeleteVoiceChannelInputBody: Swift.Equatable {
}

extension DeleteVoiceChannelInputBody: Swift.Decodable {

    public init (from decoder: Swift.Decoder) throws {
    }
}
