// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListAssistantAssociationsInputBody: Swift.Equatable {
}

extension ListAssistantAssociationsInputBody: Swift.Decodable {

    public init (from decoder: Swift.Decoder) throws {
    }
}
