// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct AttachInstancesInput: Swift.Equatable {
    /// The name of the Auto Scaling group.
    /// This member is required.
    public var autoScalingGroupName: Swift.String?
    /// The IDs of the instances. You can specify up to 20 instances.
    public var instanceIds: [Swift.String]?

    public init (
        autoScalingGroupName: Swift.String? = nil,
        instanceIds: [Swift.String]? = nil
    )
    {
        self.autoScalingGroupName = autoScalingGroupName
        self.instanceIds = instanceIds
    }
}
