// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct DescribeFirewallPolicyOutputResponseBody: Swift.Equatable {
    let updateToken: Swift.String?
    let firewallPolicyResponse: NetworkFirewallClientTypes.FirewallPolicyResponse?
    let firewallPolicy: NetworkFirewallClientTypes.FirewallPolicy?
}

extension DescribeFirewallPolicyOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case firewallPolicy = "FirewallPolicy"
        case firewallPolicyResponse = "FirewallPolicyResponse"
        case updateToken = "UpdateToken"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let updateTokenDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .updateToken)
        updateToken = updateTokenDecoded
        let firewallPolicyResponseDecoded = try containerValues.decodeIfPresent(NetworkFirewallClientTypes.FirewallPolicyResponse.self, forKey: .firewallPolicyResponse)
        firewallPolicyResponse = firewallPolicyResponseDecoded
        let firewallPolicyDecoded = try containerValues.decodeIfPresent(NetworkFirewallClientTypes.FirewallPolicy.self, forKey: .firewallPolicy)
        firewallPolicy = firewallPolicyDecoded
    }
}
