// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension CreateParticipantConnectionInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        return "/participant/connection"
    }
}
