// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension MqClientTypes {
    /// The broker's deployment mode.
    public enum DeploymentMode: Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Codable, Swift.Hashable {
        case activeStandbyMultiAz
        case clusterMultiAz
        case singleInstance
        case sdkUnknown(Swift.String)

        public static var allCases: [DeploymentMode] {
            return [
                .activeStandbyMultiAz,
                .clusterMultiAz,
                .singleInstance,
                .sdkUnknown("")
            ]
        }
        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }
        public var rawValue: Swift.String {
            switch self {
            case .activeStandbyMultiAz: return "ACTIVE_STANDBY_MULTI_AZ"
            case .clusterMultiAz: return "CLUSTER_MULTI_AZ"
            case .singleInstance: return "SINGLE_INSTANCE"
            case let .sdkUnknown(s): return s
            }
        }
        public init(from decoder: Swift.Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(RawValue.self)
            self = DeploymentMode(rawValue: rawValue) ?? DeploymentMode.sdkUnknown(rawValue)
        }
    }
}
