// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DescribeBrokerEngineTypesOutputResponse: Swift.Equatable {
    /// List of available engine types and versions.
    public var brokerEngineTypes: [MqClientTypes.BrokerEngineType]?
    /// Required. The maximum number of engine types that can be returned per page (20 by default). This value must be an integer from 5 to 100.
    public var maxResults: Swift.Int?
    /// The token that specifies the next page of results Amazon MQ should return. To request the first page, leave nextToken empty.
    public var nextToken: Swift.String?

    public init (
        brokerEngineTypes: [MqClientTypes.BrokerEngineType]? = nil,
        maxResults: Swift.Int? = nil,
        nextToken: Swift.String? = nil
    )
    {
        self.brokerEngineTypes = brokerEngineTypes
        self.maxResults = maxResults
        self.nextToken = nextToken
    }
}
