// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct PutRepositoryCatalogDataInputBody: Swift.Equatable {
    let registryId: Swift.String?
    let repositoryName: Swift.String?
    let catalogData: EcrPublicClientTypes.RepositoryCatalogDataInput?
}

extension PutRepositoryCatalogDataInputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case catalogData
        case registryId
        case repositoryName
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let registryIdDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .registryId)
        registryId = registryIdDecoded
        let repositoryNameDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .repositoryName)
        repositoryName = repositoryNameDecoded
        let catalogDataDecoded = try containerValues.decodeIfPresent(EcrPublicClientTypes.RepositoryCatalogDataInput.self, forKey: .catalogData)
        catalogData = catalogDataDecoded
    }
}
