// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct CreateProjectOutputResponse: Swift.Equatable {
    /// The name of the project that you created.
    /// This member is required.
    public var name: Swift.String?

    public init (
        name: Swift.String? = nil
    )
    {
        self.name = name
    }
}
