// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ListBillingGroupCostReportsOutputResponse: Swift.Equatable {
    /// A list of BillingGroupCostReportElement retrieved.
    public var billingGroupCostReports: [BillingconductorClientTypes.BillingGroupCostReportElement]?
    /// The pagination token used on subsequent calls to get reports.
    public var nextToken: Swift.String?

    public init (
        billingGroupCostReports: [BillingconductorClientTypes.BillingGroupCostReportElement]? = nil,
        nextToken: Swift.String? = nil
    )
    {
        self.billingGroupCostReports = billingGroupCostReports
        self.nextToken = nextToken
    }
}
