// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Represents the notification attributes for a list of identities.
public struct GetIdentityNotificationAttributesOutputResponse: Swift.Equatable {
    /// A map of Identity to IdentityNotificationAttributes.
    /// This member is required.
    public var notificationAttributes: [Swift.String:SesClientTypes.IdentityNotificationAttributes]?

    public init (
        notificationAttributes: [Swift.String:SesClientTypes.IdentityNotificationAttributes]? = nil
    )
    {
        self.notificationAttributes = notificationAttributes
    }
}
