// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct InvalidSnsTopicExceptionBody: Swift.Equatable {
    let topic: Swift.String?
    let message: Swift.String?
}

extension InvalidSnsTopicExceptionBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case topic = "Topic"
        case message
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let topicDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .topic)
        topic = topicDecoded
        let messageDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .message)
        message = messageDecoded
    }
}
