// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension SesClientTypes {
    /// Represents sending statistics data. Each SendDataPoint contains statistics for a 15-minute period of sending activity.
    public struct SendDataPoint: Swift.Equatable {
        /// Number of emails that have bounced.
        public var bounces: Swift.Int
        /// Number of unwanted emails that were rejected by recipients.
        public var complaints: Swift.Int
        /// Number of emails that have been sent.
        public var deliveryAttempts: Swift.Int
        /// Number of emails rejected by Amazon SES.
        public var rejects: Swift.Int
        /// Time of the data point.
        public var timestamp: ClientRuntime.Date?

        public init (
            bounces: Swift.Int = 0,
            complaints: Swift.Int = 0,
            deliveryAttempts: Swift.Int = 0,
            rejects: Swift.Int = 0,
            timestamp: ClientRuntime.Date? = nil
        )
        {
            self.bounces = bounces
            self.complaints = complaints
            self.deliveryAttempts = deliveryAttempts
            self.rejects = rejects
            self.timestamp = timestamp
        }
    }

}
