// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ExportProjectInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        guard let projectId = projectId else {
            return nil
        }
        return "/exports/\(projectId.urlPercentEncoding())"
    }
}
