// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension PanoramaClientTypes {
    public enum DeviceType: Swift.Equatable, Swift.RawRepresentable, Swift.CaseIterable, Swift.Codable, Swift.Hashable {
        case panoramaAppliance
        case panoramaApplianceDeveloperKit
        case sdkUnknown(Swift.String)

        public static var allCases: [DeviceType] {
            return [
                .panoramaAppliance,
                .panoramaApplianceDeveloperKit,
                .sdkUnknown("")
            ]
        }
        public init?(rawValue: Swift.String) {
            let value = Self.allCases.first(where: { $0.rawValue == rawValue })
            self = value ?? Self.sdkUnknown(rawValue)
        }
        public var rawValue: Swift.String {
            switch self {
            case .panoramaAppliance: return "PANORAMA_APPLIANCE"
            case .panoramaApplianceDeveloperKit: return "PANORAMA_APPLIANCE_DEVELOPER_KIT"
            case let .sdkUnknown(s): return s
            }
        }
        public init(from decoder: Swift.Decoder) throws {
            let container = try decoder.singleValueContainer()
            let rawValue = try container.decode(RawValue.self)
            self = DeviceType(rawValue: rawValue) ?? DeviceType.sdkUnknown(rawValue)
        }
    }
}
