// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct StartAssessmentOutputResponse: Swift.Equatable {
    /// The ID of the assessment.
    public var assessmentId: Swift.String?

    public init (
        assessmentId: Swift.String? = nil
    )
    {
        self.assessmentId = assessmentId
    }
}
