// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct StopExperimentInput: Swift.Equatable {
    /// The ID of the experiment.
    /// This member is required.
    public var id: Swift.String?

    public init (
        id: Swift.String? = nil
    )
    {
        self.id = id
    }
}
