// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteIPSetInput: Swift.Equatable {
    /// The value returned by the most recent call to [GetChangeToken].
    /// This member is required.
    public var changeToken: Swift.String?
    /// The IPSetId of the [IPSet] that you want to delete. IPSetId is returned by [CreateIPSet] and by [ListIPSets].
    /// This member is required.
    public var iPSetId: Swift.String?

    public init (
        changeToken: Swift.String? = nil,
        iPSetId: Swift.String? = nil
    )
    {
        self.changeToken = changeToken
        self.iPSetId = iPSetId
    }
}
