// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeleteLoggingConfigurationInput: Swift.Equatable {
    /// The Amazon Resource Name (ARN) of the web ACL from which you want to delete the [LoggingConfiguration].
    /// This member is required.
    public var resourceArn: Swift.String?

    public init (
        resourceArn: Swift.String? = nil
    )
    {
        self.resourceArn = resourceArn
    }
}
