// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct GetIPSetOutputResponseBody: Swift.Equatable {
    let iPSet: WafRegionalClientTypes.IPSet?
}

extension GetIPSetOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case iPSet = "IPSet"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let iPSetDecoded = try containerValues.decodeIfPresent(WafRegionalClientTypes.IPSet.self, forKey: .iPSet)
        iPSet = iPSetDecoded
    }
}
