// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension DescribeUpdateInput: ClientRuntime.QueryItemProvider {
    public var queryItems: [ClientRuntime.URLQueryItem] {
        var items = [ClientRuntime.URLQueryItem]()
        if let nodegroupName = nodegroupName {
            let nodegroupNameQueryItem = ClientRuntime.URLQueryItem(name: "nodegroupName".urlPercentEncoding(), value: Swift.String(nodegroupName).urlPercentEncoding())
            items.append(nodegroupNameQueryItem)
        }
        if let addonName = addonName {
            let addonNameQueryItem = ClientRuntime.URLQueryItem(name: "addonName".urlPercentEncoding(), value: Swift.String(addonName).urlPercentEncoding())
            items.append(addonNameQueryItem)
        }
        return items
    }
}
