// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetModelTemplateInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        guard let restApiId = restApiId else {
            return nil
        }
        guard let modelName = modelName else {
            return nil
        }
        return "/restapis/\(restApiId.urlPercentEncoding())/models/\(modelName.urlPercentEncoding())/default_template"
    }
}
