// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension ElasticBeanstalkClientTypes.MaxCountRule: Swift.Codable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case deleteSourceFromS3 = "DeleteSourceFromS3"
        case enabled = "Enabled"
        case maxCount = "MaxCount"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var container = encoder.container(keyedBy: ClientRuntime.Key.self)
        if let deleteSourceFromS3 = deleteSourceFromS3 {
            try container.encode(deleteSourceFromS3, forKey: ClientRuntime.Key("DeleteSourceFromS3"))
        }
        if let enabled = enabled {
            try container.encode(enabled, forKey: ClientRuntime.Key("Enabled"))
        }
        if let maxCount = maxCount {
            try container.encode(maxCount, forKey: ClientRuntime.Key("MaxCount"))
        }
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let enabledDecoded = try containerValues.decodeIfPresent(Swift.Bool.self, forKey: .enabled)
        enabled = enabledDecoded
        let maxCountDecoded = try containerValues.decodeIfPresent(Swift.Int.self, forKey: .maxCount)
        maxCount = maxCountDecoded
        let deleteSourceFromS3Decoded = try containerValues.decodeIfPresent(Swift.Bool.self, forKey: .deleteSourceFromS3)
        deleteSourceFromS3 = deleteSourceFromS3Decoded
    }
}
