// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetEvidenceFoldersByAssessmentOutputResponse: Swift.Equatable {
    /// The list of evidence folders that the GetEvidenceFoldersByAssessment API returned.
    public var evidenceFolders: [AuditManagerClientTypes.AssessmentEvidenceFolder]?
    /// The pagination token that's used to fetch the next set of results.
    public var nextToken: Swift.String?

    public init (
        evidenceFolders: [AuditManagerClientTypes.AssessmentEvidenceFolder]? = nil,
        nextToken: Swift.String? = nil
    )
    {
        self.evidenceFolders = evidenceFolders
        self.nextToken = nextToken
    }
}
