// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GetGameConfigurationInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        guard let gameName = gameName else {
            return nil
        }
        return "/game/\(gameName.urlPercentEncoding())/configuration"
    }
}
