// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DescribeSubnetGroupsOutputResponse: Swift.Equatable {
    /// An optional argument to pass in case the total number of records exceeds the value of MaxResults. If nextToken is returned, there are more results available. The value of nextToken is a unique pagination token for each page. Make the call again using the returned token to retrieve the next page. Keep all other arguments unchanged.
    public var nextToken: Swift.String?
    /// A list of subnet groups. Each element in the list contains detailed information about one group.
    public var subnetGroups: [MemoryDbClientTypes.SubnetGroup]?

    public init (
        nextToken: Swift.String? = nil,
        subnetGroups: [MemoryDbClientTypes.SubnetGroup]? = nil
    )
    {
        self.nextToken = nextToken
        self.subnetGroups = subnetGroups
    }
}
