// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension MemoryDbClientTypes {
    /// Represents the subnet associated with a cluster. This parameter refers to subnets defined in Amazon Virtual Private Cloud (Amazon VPC) and used with MemoryDB.
    public struct Subnet: Swift.Equatable {
        /// The Availability Zone where the subnet resides
        public var availabilityZone: MemoryDbClientTypes.AvailabilityZone?
        /// The unique identifier for the subnet.
        public var identifier: Swift.String?

        public init (
            availabilityZone: MemoryDbClientTypes.AvailabilityZone? = nil,
            identifier: Swift.String? = nil
        )
        {
            self.availabilityZone = availabilityZone
            self.identifier = identifier
        }
    }

}
