// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension CreateProgramInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case adBreaks = "AdBreaks"
        case liveSourceName = "LiveSourceName"
        case scheduleConfiguration = "ScheduleConfiguration"
        case sourceLocationName = "SourceLocationName"
        case vodSourceName = "VodSourceName"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let adBreaks = adBreaks {
            var adBreaksContainer = encodeContainer.nestedUnkeyedContainer(forKey: .adBreaks)
            for __listofadbreak0 in adBreaks {
                try adBreaksContainer.encode(__listofadbreak0)
            }
        }
        if let liveSourceName = self.liveSourceName {
            try encodeContainer.encode(liveSourceName, forKey: .liveSourceName)
        }
        if let scheduleConfiguration = self.scheduleConfiguration {
            try encodeContainer.encode(scheduleConfiguration, forKey: .scheduleConfiguration)
        }
        if let sourceLocationName = self.sourceLocationName {
            try encodeContainer.encode(sourceLocationName, forKey: .sourceLocationName)
        }
        if let vodSourceName = self.vodSourceName {
            try encodeContainer.encode(vodSourceName, forKey: .vodSourceName)
        }
    }
}
