// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct DetectSentimentInputBody: Swift.Equatable {
    let text: Swift.String?
    let languageCode: ComprehendClientTypes.LanguageCode?
}

extension DetectSentimentInputBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case languageCode = "LanguageCode"
        case text = "Text"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let textDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .text)
        text = textDecoded
        let languageCodeDecoded = try containerValues.decodeIfPresent(ComprehendClientTypes.LanguageCode.self, forKey: .languageCode)
        languageCode = languageCodeDecoded
    }
}
