// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct ListPiiEntitiesDetectionJobsOutputResponse: Swift.Equatable {
    /// Identifies the next page of results to return.
    public var nextToken: Swift.String?
    /// A list containing the properties of each job that is returned.
    public var piiEntitiesDetectionJobPropertiesList: [ComprehendClientTypes.PiiEntitiesDetectionJobProperties]?

    public init (
        nextToken: Swift.String? = nil,
        piiEntitiesDetectionJobPropertiesList: [ComprehendClientTypes.PiiEntitiesDetectionJobProperties]? = nil
    )
    {
        self.nextToken = nextToken
        self.piiEntitiesDetectionJobPropertiesList = piiEntitiesDetectionJobPropertiesList
    }
}
