// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct DescribeFleetAdvisorSchemasOutputResponseBody: Swift.Equatable {
    let fleetAdvisorSchemas: [DatabaseMigrationClientTypes.SchemaResponse]?
    let nextToken: Swift.String?
}

extension DescribeFleetAdvisorSchemasOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case fleetAdvisorSchemas = "FleetAdvisorSchemas"
        case nextToken = "NextToken"
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let fleetAdvisorSchemasContainer = try containerValues.decodeIfPresent([DatabaseMigrationClientTypes.SchemaResponse?].self, forKey: .fleetAdvisorSchemas)
        var fleetAdvisorSchemasDecoded0:[DatabaseMigrationClientTypes.SchemaResponse]? = nil
        if let fleetAdvisorSchemasContainer = fleetAdvisorSchemasContainer {
            fleetAdvisorSchemasDecoded0 = [DatabaseMigrationClientTypes.SchemaResponse]()
            for structure0 in fleetAdvisorSchemasContainer {
                if let structure0 = structure0 {
                    fleetAdvisorSchemasDecoded0?.append(structure0)
                }
            }
        }
        fleetAdvisorSchemas = fleetAdvisorSchemasDecoded0
        let nextTokenDecoded = try containerValues.decodeIfPresent(Swift.String.self, forKey: .nextToken)
        nextToken = nextTokenDecoded
    }
}
