// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension BatchDisableAlarmInput: ClientRuntime.URLPathProvider {
    public var urlPath: Swift.String? {
        return "/alarms/disable"
    }
}
