// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListCuratedEnvironmentImagesOutputResponseBody: Swift.Equatable {
    let platforms: [CodeBuildClientTypes.EnvironmentPlatform]?
}

extension ListCuratedEnvironmentImagesOutputResponseBody: Swift.Decodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case platforms
    }

    public init (from decoder: Swift.Decoder) throws {
        let containerValues = try decoder.container(keyedBy: CodingKeys.self)
        let platformsContainer = try containerValues.decodeIfPresent([CodeBuildClientTypes.EnvironmentPlatform?].self, forKey: .platforms)
        var platformsDecoded0:[CodeBuildClientTypes.EnvironmentPlatform]? = nil
        if let platformsContainer = platformsContainer {
            platformsDecoded0 = [CodeBuildClientTypes.EnvironmentPlatform]()
            for structure0 in platformsContainer {
                if let structure0 = structure0 {
                    platformsDecoded0?.append(structure0)
                }
            }
        }
        platforms = platformsDecoded0
    }
}
