// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct SendCommandOutputResponse: Swift.Equatable {
    /// The request as it was received by Systems Manager. Also provides the command ID which can be used future references to this request.
    public var command: SsmClientTypes.Command?

    public init (
        command: SsmClientTypes.Command? = nil
    )
    {
        self.command = command
    }
}
