// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension IoTSiteWiseClientTypes {
    /// The file format of the data.
    public struct FileFormat: Swift.Equatable {
        /// The .csv file format.
        public var csv: IoTSiteWiseClientTypes.Csv?

        public init (
            csv: IoTSiteWiseClientTypes.Csv? = nil
        )
        {
            self.csv = csv
        }
    }

}
