// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateOutpostOutputResponse: Swift.Equatable {
    /// Information about an Outpost.
    public var outpost: OutpostsClientTypes.Outpost?

    public init (
        outpost: OutpostsClientTypes.Outpost? = nil
    )
    {
        self.outpost = outpost
    }
}
