// Code generated by smithy-swift-codegen. DO NOT EDIT!



/// Container for the parameters to the [DescribeOutboundCrossClusterSearchConnections] operation.
public struct DescribeOutboundCrossClusterSearchConnectionsInput: Swift.Equatable {
    /// A list of filters used to match properties for outbound cross-cluster search connection. Available [Filter] names for this operation are:
    ///
    /// * cross-cluster-search-connection-id
    ///
    /// * destination-domain-info.domain-name
    ///
    /// * destination-domain-info.owner-id
    ///
    /// * destination-domain-info.region
    ///
    /// * source-domain-info.domain-name
    public var filters: [ElasticsearchClientTypes.Filter]?
    /// Set this value to limit the number of results returned. If not specified, defaults to 100.
    public var maxResults: Swift.Int
    /// NextToken is sent in case the earlier API call results contain the NextToken. It is used for pagination.
    public var nextToken: Swift.String?

    public init (
        filters: [ElasticsearchClientTypes.Filter]? = nil,
        maxResults: Swift.Int = 0,
        nextToken: Swift.String? = nil
    )
    {
        self.filters = filters
        self.maxResults = maxResults
        self.nextToken = nextToken
    }
}
