// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension CodePipelineClientTypes {
    /// Represents revision details of an artifact.
    public struct ArtifactRevision: Swift.Equatable {
        /// The date and time when the most recent revision of the artifact was created, in timestamp format.
        public var created: ClientRuntime.Date?
        /// The name of an artifact. This name might be system-generated, such as "MyApp", or defined by the user when an action is created.
        public var name: Swift.String?
        /// An additional identifier for a revision, such as a commit date or, for artifacts stored in Amazon S3 buckets, the ETag value.
        public var revisionChangeIdentifier: Swift.String?
        /// The revision ID of the artifact.
        public var revisionId: Swift.String?
        /// Summary information about the most recent revision of the artifact. For GitHub and AWS CodeCommit repositories, the commit message. For Amazon S3 buckets or actions, the user-provided content of a codepipeline-artifact-revision-summary key specified in the object metadata.
        public var revisionSummary: Swift.String?
        /// The commit ID for the artifact revision. For artifacts stored in GitHub or AWS CodeCommit repositories, the commit ID is linked to a commit details page.
        public var revisionUrl: Swift.String?

        public init (
            created: ClientRuntime.Date? = nil,
            name: Swift.String? = nil,
            revisionChangeIdentifier: Swift.String? = nil,
            revisionId: Swift.String? = nil,
            revisionSummary: Swift.String? = nil,
            revisionUrl: Swift.String? = nil
        )
        {
            self.created = created
            self.name = name
            self.revisionChangeIdentifier = revisionChangeIdentifier
            self.revisionId = revisionId
            self.revisionSummary = revisionSummary
            self.revisionUrl = revisionUrl
        }
    }

}
