// Code generated by smithy-swift-codegen. DO NOT EDIT!

import AWSClientRuntime

public enum GetReusableDelegationSetOutputError: Swift.Error, Swift.Equatable {
    case delegationSetNotReusable(DelegationSetNotReusable)
    case invalidInput(InvalidInput)
    case noSuchDelegationSet(NoSuchDelegationSet)
    case unknown(UnknownAWSHttpServiceError)
}
