// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

struct ListHostedZonesByVPCInputBody: Swift.Equatable {
}

extension ListHostedZonesByVPCInputBody: Swift.Decodable {

    public init (from decoder: Swift.Decoder) throws {
    }
}
