// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension WorkMailClientTypes {
    /// The configuration applied to an organization's folders by its retention policy.
    public struct FolderConfiguration: Swift.Equatable {
        /// The action to take on the folder contents at the end of the folder configuration period.
        /// This member is required.
        public var action: WorkMailClientTypes.RetentionAction?
        /// The folder name.
        /// This member is required.
        public var name: WorkMailClientTypes.FolderName?
        /// The number of days for which the folder-configuration action applies.
        public var period: Swift.Int?

        public init (
            action: WorkMailClientTypes.RetentionAction? = nil,
            name: WorkMailClientTypes.FolderName? = nil,
            period: Swift.Int? = nil
        )
        {
            self.action = action
            self.name = name
            self.period = period
        }
    }

}
