// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension GenerateChangeSetInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case appId
        case changesetFormat
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let appId = self.appId {
            try encodeContainer.encode(appId, forKey: .appId)
        }
        if let changesetFormat = self.changesetFormat {
            try encodeContainer.encode(changesetFormat.rawValue, forKey: .changesetFormat)
        }
    }
}
