// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

public struct ListFlowDefinitionsInput: Swift.Equatable {
    /// A filter that returns only flow definitions with a creation time greater than or equal to the specified timestamp.
    public var creationTimeAfter: ClientRuntime.Date?
    /// A filter that returns only flow definitions that were created before the specified timestamp.
    public var creationTimeBefore: ClientRuntime.Date?
    /// The total number of items to return. If the total number of available items is more than the value specified in MaxResults, then a NextToken will be provided in the output that you can use to resume pagination.
    public var maxResults: Swift.Int?
    /// A token to resume pagination.
    public var nextToken: Swift.String?
    /// An optional value that specifies whether you want the results sorted in Ascending or Descending order.
    public var sortOrder: SageMakerClientTypes.SortOrder?

    public init (
        creationTimeAfter: ClientRuntime.Date? = nil,
        creationTimeBefore: ClientRuntime.Date? = nil,
        maxResults: Swift.Int? = nil,
        nextToken: Swift.String? = nil,
        sortOrder: SageMakerClientTypes.SortOrder? = nil
    )
    {
        self.creationTimeAfter = creationTimeAfter
        self.creationTimeBefore = creationTimeBefore
        self.maxResults = maxResults
        self.nextToken = nextToken
        self.sortOrder = sortOrder
    }
}
