// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SageMakerClientTypes {
    /// Specifies ranges of integer, continuous, and categorical hyperparameters that a hyperparameter tuning job searches. The hyperparameter tuning job launches training jobs with hyperparameter values within these ranges to find the combination of values that result in the training job with the best performance as measured by the objective metric of the hyperparameter tuning job. The maximum number of items specified for Array Members refers to the maximum number of hyperparameters for each range and also the maximum for the hyperparameter tuning job itself. That is, the sum of the number of hyperparameters for all the ranges can't exceed the maximum number specified.
    public struct ParameterRanges: Swift.Equatable {
        /// The array of [CategoricalParameterRange] objects that specify ranges of categorical hyperparameters that a hyperparameter tuning job searches.
        public var categoricalParameterRanges: [SageMakerClientTypes.CategoricalParameterRange]?
        /// The array of [ContinuousParameterRange] objects that specify ranges of continuous hyperparameters that a hyperparameter tuning job searches.
        public var continuousParameterRanges: [SageMakerClientTypes.ContinuousParameterRange]?
        /// The array of [IntegerParameterRange] objects that specify ranges of integer hyperparameters that a hyperparameter tuning job searches.
        public var integerParameterRanges: [SageMakerClientTypes.IntegerParameterRange]?

        public init (
            categoricalParameterRanges: [SageMakerClientTypes.CategoricalParameterRange]? = nil,
            continuousParameterRanges: [SageMakerClientTypes.ContinuousParameterRange]? = nil,
            integerParameterRanges: [SageMakerClientTypes.IntegerParameterRange]? = nil
        )
        {
            self.categoricalParameterRanges = categoricalParameterRanges
            self.continuousParameterRanges = continuousParameterRanges
            self.integerParameterRanges = integerParameterRanges
        }
    }

}
