// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SageMakerClientTypes {
    /// The resolved attributes.
    public struct ResolvedAttributes: Swift.Equatable {
        /// Specifies a metric to minimize or maximize as the objective of a job.
        public var autoMLJobObjective: SageMakerClientTypes.AutoMLJobObjective?
        /// How long a job is allowed to run, or how many candidates a job is allowed to generate.
        public var completionCriteria: SageMakerClientTypes.AutoMLJobCompletionCriteria?
        /// The problem type.
        public var problemType: SageMakerClientTypes.ProblemType?

        public init (
            autoMLJobObjective: SageMakerClientTypes.AutoMLJobObjective? = nil,
            completionCriteria: SageMakerClientTypes.AutoMLJobCompletionCriteria? = nil,
            problemType: SageMakerClientTypes.ProblemType? = nil
        )
        {
            self.autoMLJobObjective = autoMLJobObjective
            self.completionCriteria = completionCriteria
            self.problemType = problemType
        }
    }

}
