// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SageMakerClientTypes {
    /// The Liquid template for the worker user interface.
    public struct UiTemplate: Swift.Equatable {
        /// The content of the Liquid template for the worker user interface.
        /// This member is required.
        public var content: Swift.String?

        public init (
            content: Swift.String? = nil
        )
        {
            self.content = content
        }
    }

}
