// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct UpdateFeatureGroupOutputResponse: Swift.Equatable {
    /// The Amazon Resource Number (ARN) of the feature group that you're updating.
    /// This member is required.
    public var featureGroupArn: Swift.String?

    public init (
        featureGroupArn: Swift.String? = nil
    )
    {
        self.featureGroupArn = featureGroupArn
    }
}
