// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct DeauthorizeConnectionInput: Swift.Equatable {
    /// The name of the connection to remove authorization from.
    /// This member is required.
    public var name: Swift.String?

    public init (
        name: Swift.String? = nil
    )
    {
        self.name = name
    }
}
