// Code generated by smithy-swift-codegen. DO NOT EDIT!



public struct GetFirewallRuleGroupPolicyInput: Swift.Equatable {
    /// The ARN (Amazon Resource Name) for the rule group.
    /// This member is required.
    public var arn: Swift.String?

    public init (
        arn: Swift.String? = nil
    )
    {
        self.arn = arn
    }
}
