// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

extension UpdateResolverDnssecConfigInput: Swift.Encodable {
    enum CodingKeys: Swift.String, Swift.CodingKey {
        case resourceId = "ResourceId"
        case validation = "Validation"
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var encodeContainer = encoder.container(keyedBy: CodingKeys.self)
        if let resourceId = self.resourceId {
            try encodeContainer.encode(resourceId, forKey: .resourceId)
        }
        if let validation = self.validation {
            try encodeContainer.encode(validation.rawValue, forKey: .validation)
        }
    }
}
