// Code generated by smithy-swift-codegen. DO NOT EDIT!



extension SecurityHubClientTypes {
    /// An adjustment to the CVSS metric.
    public struct Adjustment: Swift.Equatable {
        /// The metric to adjust.
        public var metric: Swift.String?
        /// The reason for the adjustment.
        public var reason: Swift.String?

        public init (
            metric: Swift.String? = nil,
            reason: Swift.String? = nil
        )
        {
            self.metric = metric
            self.reason = reason
        }
    }

}
